 package com.raj;

import java.sql.Connection;
import java.sql.DriverManager;

import java.sql.SQLException;
import java.sql.Statement;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class Workers extends javax.swing.JFrame {
    
    Connection connection;
    Statement statement;
    ResultSet resultSet;
    int currentRow = 0;

    public Workers() {
        initComponents();
        doConnect();
    }
    
    public void doConnect(){
        try {
            //CNNECT TO THE DATABASE
           String host = "jdbc:mysql://localhost:3306/employees?zeroDateTimeBehavior=convertToNull";
           String userName = "root";
           String password = "";
           Connection connection = DriverManager.getConnection(host, userName, password);
           //EXECUTE SOME SQL AND LOAD RECORDS INTO RESULTSET
           //statement = con.createStatement ();
           
           statement = connection.createStatement (ResultSet.TYPE_SCROLL_INSENSITIVE,
                                                   ResultSet.CONCUR_UPDATABLE );
           String SQL = "SELECT *FROM Workers";
           resultSet = statement.executeQuery( SQL );
           
           //MOVE THE CURSOR TO THE FIRST RECORD AND GET THE DATA
           
           resultSet.next();
           int id_col = resultSet.getInt("ID");
           
           String id = Integer.toString(id_col);
           String firstName = resultSet.getString("First_Name");
           String secondName= resultSet.getString("Last_Name");
           String job = resultSet.getString("Job_Title");
           
           //DISPLAY THE FIRST RECORD IN THE NEXT FIELDS
           idTextField.setText(id);
           firstNameTextField.setText(firstName);
           secondNameTextField.setText(secondName);
           jobTitleTextField.setText(job);
        }
        catch (SQLException error){
            JOptionPane.showMessageDialog(this,error.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        secondNameTextField = new javax.swing.JTextField();
        jobTitleTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        firstButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        updateRecordButton = new javax.swing.JButton();
        deleteRecordButton = new javax.swing.JButton();
        javax.swing.JButton newRecordButton = new javax.swing.JButton();
        javax.swing.JButton saveNewRecordButton = new javax.swing.JButton();
        cancelNewRecordButton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText("ID");

        jLabel3.setText("Name");

        jLabel4.setText("Second Name");

        jLabel6.setText("Job Title");

        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jobTitleTextField)
                        .addGap(271, 271, 271))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(secondNameTextField)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jobTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        firstButton.setText("First");
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });

        previousButton.setText("Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        lastButton.setText("Last");
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(firstButton)
                .addGap(47, 47, 47)
                .addComponent(previousButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton)
                .addGap(88, 88, 88)
                .addComponent(lastButton)
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstButton)
                    .addComponent(previousButton)
                    .addComponent(nextButton)
                    .addComponent(lastButton))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        updateRecordButton.setText("Update Record");
        updateRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRecordButtonActionPerformed(evt);
            }
        });

        deleteRecordButton.setText("Delete Record");
        deleteRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRecordButtonActionPerformed(evt);
            }
        });

        newRecordButton.setText("New Record");
        newRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRecordButtonActionPerformed(evt);
            }
        });

        saveNewRecordButton.setText("Save New Record");
        saveNewRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewRecordButtonActionPerformed(evt);
            }
        });

        cancelNewRecordButton.setText("Cancel New Record");
        cancelNewRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelNewRecordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(updateRecordButton)
                .addGap(103, 103, 103)
                .addComponent(deleteRecordButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newRecordButton)
                .addGap(87, 87, 87))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(saveNewRecordButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(cancelNewRecordButton)
                .addGap(186, 186, 186))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateRecordButton)
                    .addComponent(deleteRecordButton)
                    .addComponent(newRecordButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveNewRecordButton)
                    .addComponent(cancelNewRecordButton))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(435, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        // TODO add your handling code here:
        try {
             resultSet.last();
             
             int id_col = resultSet.getInt("ID");
           
           String id = Integer.toString(id_col);
           String firstName = resultSet.getString("First_Name");
           String secondName= resultSet.getString("Last_Name");
           String job = resultSet.getString("Job_Title");
           
           idTextField.setText(id);
           firstNameTextField.setText(firstName);
           secondNameTextField.setText(secondName);
           jobTitleTextField.setText(job);
        }
        catch (SQLException error){
            JOptionPane.showMessageDialog(this,error.getMessage());
        }
    }//GEN-LAST:event_lastButtonActionPerformed

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
        // TODO add your handling code here:
        try {
             resultSet.first();
             
             int id_col = resultSet.getInt("ID");
           
           String id = Integer.toString(id_col);
           String firstName = resultSet.getString("First_Name");
           String secondName= resultSet.getString("Last_Name");
           String job = resultSet.getString("Job_Title");
           
           idTextField.setText(id);
           firstNameTextField.setText(firstName);
           secondNameTextField.setText(secondName);
           jobTitleTextField.setText(job);
        }
        catch (SQLException error){
            JOptionPane.showMessageDialog(this,error.getMessage());
        }
    }//GEN-LAST:event_firstButtonActionPerformed

    private void updateRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRecordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateRecordButtonActionPerformed

    private void deleteRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRecordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteRecordButtonActionPerformed

    private void newRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRecordButtonActionPerformed
        // TODO add your handling code here:
        try {
            currentRow = resultSet.getRow();
            
            idTextField.setText("");
            firstNameTextField.setText("");
            secondNameTextField.setText("");
            jobTitleTextField.setText("");
            
            idTextField.setEnabled(false);
            firstButton.setEnabled(false);
            previousButton.setEnabled(false);
            nextButton.setEnabled(false);
            lastButton.setEnabled(false);
            updateRecordButton.setEnabled(false);
            deleteRecordButton.setEnabled(false);
            //newRecordButton.setEnabled(false);
            //saveNewRecordButton.setEnabled(true);
            cancelNewRecordButton.setEnabled(true);
        }
         catch (SQLException error){
            JOptionPane.showMessageDialog(this,error.getMessage());
        }
    }//GEN-LAST:event_newRecordButtonActionPerformed

    private void saveNewRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewRecordButtonActionPerformed
        String first = firstNameTextField.getText();
        String last = secondNameTextField.getText();
        String job = jobTitleTextField.getText();
        
        try {
            resultSet.moveToInsertRow();
            
            resultSet.updateString("First_Name", first);
            resultSet.updateString("Last_Name", last);
            resultSet.updateString("Job_Title", job);
            
            resultSet.insertRow();
            statement.close();
            resultSet.close();
            
            String host = "jdbc:mysql://localhost:3306/employees?zeroDateTimeBehavior=convertToNull";
            String userName = "root";
            String userPassword = "";
            Connection connection = DriverManager.getConnection(host, userName, userPassword);
            
            statement = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            
            String SQL = "SELECT * FROM `workers` WHERE 1 ";
            
            resultSet = statement.executeQuery(SQL);
            resultSet.next();
            int id_col = resultSet.getInt("ID");
            String id = Integer.toString(id_col);
            String first2 = resultSet.getString("First_Name");
            String last2 = resultSet.getString("Last_Name");
            String job2 = resultSet.getString("Job_Title");
            
            idTextField.setText(id);
            firstNameTextField.setText(first2);
            secondNameTextField.setText(last2);
            jobTitleTextField.setText(job2);
            
            idTextField.setEnabled(true);
            firstButton.setEnabled(true);
            previousButton.setEnabled(true);
            nextButton.setEnabled(true);
            lastButton.setEnabled(true);
            updateRecordButton.setEnabled(true);
            deleteRecordButton.setEnabled(true);
           // newRecordButton.setEnabled(true);
            //saveNewRecordButton.setEnabled(true);
            cancelNewRecordButton.setEnabled(true);
        }
        catch (SQLException error) {
            JOptionPane.showMessageDialog(this, error.getMessage());
        }
    }//GEN-LAST:event_saveNewRecordButtonActionPerformed

    private void cancelNewRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelNewRecordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelNewRecordButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        // TODO add your handling code here:
        try {
            
           
           if (resultSet.previous()) {
             int id_col = resultSet.getInt("ID");
           
               String id = Integer.toString(id_col);
               String firstName = resultSet.getString("First_Name");
               String secondName= resultSet.getString("Last_Name");
               String job = resultSet.getString("Job_Title");
           
               idTextField.setText(id);
               firstNameTextField.setText(firstName);
               secondNameTextField.setText(secondName);
               jobTitleTextField.setText(job);
           }
           else{
               resultSet.next();
               JOptionPane.showMessageDialog(Workers.this,"End Of File");
           }
        }
        catch (SQLException error){
            JOptionPane.showMessageDialog(this,error.getMessage());
        }
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        try {
           if (resultSet.next()) {
               resultSet.next();
             
             int id_col = resultSet.getInt("ID");
           
           String id = Integer.toString(id_col);
           String firstName = resultSet.getString("First_Name");
           String secondName= resultSet.getString("Last_Name");
           String job = resultSet.getString("Job_Title");
           
           idTextField.setText(id);
           firstNameTextField.setText(firstName);
           secondNameTextField.setText(secondName);
           jobTitleTextField.setText(job);
           }
           else{
               resultSet.next();
               JOptionPane.showMessageDialog(Workers.this,"End Of File");
           }
        }
        catch (SQLException error){
            JOptionPane.showMessageDialog(this,error.getMessage());
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Workers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelNewRecordButton;
    private javax.swing.JButton deleteRecordButton;
    private javax.swing.JButton firstButton;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jobTitleTextField;
    private javax.swing.JButton lastButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JTextField secondNameTextField;
    private javax.swing.JButton updateRecordButton;
    // End of variables declaration//GEN-END:variables
}
