package greenbridge.pkgfinal.exam;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;

import javax.swing.*;

public class AttendanceList extends javax.swing.JFrame {
    
    Connection connection;
    Statement statement;
    ResultSet resultSet;
    int currentRow = 0;
    
    public AttendanceList() {
        initComponents();
        doConnect();
    }
    
    public void doConnect(){
        try{
            
            //*************************************************************
            
            //CNNECT TO THE DATABASE
           String host = "jdbc:mysql://localhost:3306/attendance?zeroDateTimeBehavior=convertToNull";
           String userName = "root";
           String password = "";
           Connection connection = DriverManager.getConnection(host, userName, password);
           //EXECUTE SOME SQL AND LOAD RECORDS INTO RESULTSET
//           statement = con.createStatement ();
           
           statement = connection.createStatement (ResultSet.TYPE_SCROLL_INSENSITIVE,
                                                   ResultSet.CONCUR_UPDATABLE );
           String SQL = "SELECT * FROM greenbridgeattendance";
           resultSet = statement.executeQuery( SQL );
           
           //*************************************************************
           
           //MOVE THE CURSOR TO THE FIRST RECORD AND GET THE DATA
           
           resultSet.next();
           int registration_no = resultSet.getInt("Registration_No");
           
           String registration_No = Integer.toString(registration_no);
           String registration_Date = resultSet.getString("Registration_Date");
           String firstName = resultSet.getString("First_Name");
           String secondName= resultSet.getString("Second_Name");
           String course = resultSet.getString("Course");
           
           //DISPLAY THE FIRST RECORD IN THE NEXT FIELDS
           registrationNoTextField.setText(registration_No);
           registrationDateTextField.setText(registration_Date);
           firstNameTextField.setText(firstName);
           secondNameTextField.setText(secondName);
           courseTextField.setText(course);
        }
        catch (SQLException error){
            JOptionPane.showMessageDialog(this,error.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        registrationNoTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        registrationDateTextField = new javax.swing.JTextField();
        secondNameTextField = new javax.swing.JTextField();
        courseTextField = new javax.swing.JTextField();
        newButton = new javax.swing.JButton();
        saveNewRecordButton = new javax.swing.JButton();
        firstButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
        jLabel1.setText("GreenBridge Attendance List");

        jLabel2.setText("Registration_No");

        jLabel3.setText("Registration_Date");

        jLabel4.setText("First_Name");

        jLabel5.setText("Second_Name");

        jLabel6.setText("Course");

        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        newButton.setText("New Record");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        saveNewRecordButton.setText("Save New Record");
        saveNewRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewRecordButtonActionPerformed(evt);
            }
        });

        firstButton.setText("First");
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });

        previousButton.setText("Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        lastButton.setText("Last");
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstButton)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(previousButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(nextButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(lastButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(registrationNoTextField)
                                                    .addComponent(registrationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 29, 29)
                                                .addComponent(newButton))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(firstNameTextField)
                                                    .addComponent(secondNameTextField)
                                                    .addComponent(courseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(saveNewRecordButton)))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(registrationNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registrationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveNewRecordButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(secondNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(courseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstButton)
                    .addComponent(previousButton)
                    .addComponent(nextButton)
                    .addComponent(lastButton))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
        try {
        resultSet.first();
           int registration_no = resultSet.getInt("Registration_No");
           
           String registration_No = Integer.toString(registration_no);
           String registration_Date = resultSet.getString("Registration_Date");
           String firstName = resultSet.getString("First_Name");
           String secondName= resultSet.getString("Second_Name");
           String course = resultSet.getString("Course");
           
           //DISPLAY THE FIRST RECORD IN THE NEXT FIELDS
           registrationNoTextField.setText(registration_No);
           registrationDateTextField.setText(registration_Date);
           firstNameTextField.setText(firstName);
           secondNameTextField.setText(secondName);
           courseTextField.setText(course);
        }
        catch (SQLException error){
            JOptionPane.showMessageDialog(this,error.getMessage());
        }
    }//GEN-LAST:event_firstButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        try {
            
           
           if (resultSet.previous()) {
               int registration_no = resultSet.getInt("Registration_No");
           
               String registration_No = Integer.toString(registration_no);
               String registration_Date = resultSet.getString("Registration_Date");
               String firstName = resultSet.getString("First_Name");
               String secondName= resultSet.getString("Second_Name");
               String course = resultSet.getString("Course");
           
               registrationNoTextField.setText(registration_No);
               registrationDateTextField.setText(registration_Date);
               firstNameTextField.setText(firstName);
               secondNameTextField.setText(secondName);
               courseTextField.setText(course);
           }
           else{
               resultSet.next();
               JOptionPane.showMessageDialog(AttendanceList.this,"End Of File");
           }
        }
        catch (SQLException error){
            JOptionPane.showMessageDialog(this,error.getMessage());
        }
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        try {
           if (resultSet.next()) {
              int registration_no = resultSet.getInt("Registration_No");
           
               String registration_No = Integer.toString(registration_no);
               String registration_Date = resultSet.getString("Registration_Date");
               String firstName = resultSet.getString("First_Name");
               String secondName= resultSet.getString("Second_Name");
               String course = resultSet.getString("Course");
           
               registrationNoTextField.setText(registration_No);
               registrationDateTextField.setText(registration_Date);
               firstNameTextField.setText(firstName);
               secondNameTextField.setText(secondName);
               courseTextField.setText(course);
           }
           else{
               resultSet.next();
               JOptionPane.showMessageDialog(AttendanceList.this,"End Of File");
           }
        }
        catch (SQLException error){
            JOptionPane.showMessageDialog(this,error.getMessage());
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        try {
        resultSet.last();
           int registration_no = resultSet.getInt("Registration_No");
           
           String registration_No = Integer.toString(registration_no);
           String registration_Date = resultSet.getString("Registration_Date");
           String firstName = resultSet.getString("First_Name");
           String secondName= resultSet.getString("Second_Name");
           String course = resultSet.getString("Course");
           
           //DISPLAY THE FIRST RECORD IN THE NEXT FIELDS
           registrationNoTextField.setText(registration_No);
           registrationDateTextField.setText(registration_Date);
           firstNameTextField.setText(firstName);
           secondNameTextField.setText(secondName);
           courseTextField.setText(course);
        }
        catch (SQLException error){
            JOptionPane.showMessageDialog(this,error.getMessage());
        }
    }//GEN-LAST:event_lastButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        try {
            currentRow = resultSet.getRow();
            
            registrationNoTextField.setText("");
           registrationDateTextField.setText("");
           firstNameTextField.setText("");
           secondNameTextField.setText("");
           courseTextField.setText("");
            
            registrationNoTextField.setEnabled(false);
            firstButton.setEnabled(false);
            previousButton.setEnabled(false);
            nextButton.setEnabled(false);
            lastButton.setEnabled(false);
            //newRecordButton.setEnabled(false);
            //saveNewRecordButton.setEnabled(true);
        }
         catch (SQLException error){
            JOptionPane.showMessageDialog(this,error.getMessage());
        }
    }//GEN-LAST:event_newButtonActionPerformed

    private void saveNewRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewRecordButtonActionPerformed
        String date = registrationDateTextField.getText();
        String first = firstNameTextField.getText();
        String second = secondNameTextField.getText();
        String course = courseTextField.getText();
        
        try {
            resultSet.moveToInsertRow();
            
            resultSet.updateString("First_Name", first);
            resultSet.updateString("Second_Name", second);
            resultSet.updateString("Course", course);
            
            resultSet.insertRow();
            statement.close();
            resultSet.close();
            
            String host = "jdbc:mysql://localhost:3306/attendance?zeroDateTimeBehavior=convertToNull";
            String userName = "root";
            String userPassword = "";
            Connection connection = DriverManager.getConnection(host, userName, userPassword);
            
            statement = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            
            String SQL = "SELECT * FROM greenbridgeattendance ";
            
            resultSet = statement.executeQuery(SQL);
            resultSet.next();
            
            String date2 = resultSet.getString("Registration_Date");
            String first2 = resultSet.getString("First_Name");
            String second2 = resultSet.getString("Second_Name");
            String course2 = resultSet.getString("Course");
            
             int registration_no = resultSet.getInt("Registration_No");
           
           String registration_No = Integer.toString(registration_no);
           String registration_Date = resultSet.getString("Registration_Date");
           String firstName = resultSet.getString("First_Name");
           String secondName= resultSet.getString("Second_Name");
           course = resultSet.getString("Course");
           
           //DISPLAY THE FIRST RECORD IN THE NEXT FIELDS
           registrationNoTextField.setText(registration_No);
           registrationDateTextField.setText(registration_Date);
           firstNameTextField.setText(firstName);
           secondNameTextField.setText(secondName);
           courseTextField.setText(course);
            
           registrationNoTextField.setEnabled(true);
            firstButton.setEnabled(true);
            previousButton.setEnabled(true);
            nextButton.setEnabled(true);
            lastButton.setEnabled(true);
        }
        catch (SQLException error) {
            JOptionPane.showMessageDialog(this, error.getMessage());
        }
    }//GEN-LAST:event_saveNewRecordButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendanceList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField courseTextField;
    private javax.swing.JButton firstButton;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lastButton;
    private javax.swing.JButton newButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JTextField registrationDateTextField;
    private javax.swing.JTextField registrationNoTextField;
    private javax.swing.JButton saveNewRecordButton;
    private javax.swing.JTextField secondNameTextField;
    // End of variables declaration//GEN-END:variables
}
