
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.FileOutputStream;
import javax.swing.*;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;

public class Login extends JFrame {

    public String hostName = "localhost:3306";
    public String userName = "root";
    public String password = "";
    public String database = "impigerinternapp";

    boolean loginL = true;

    PreparedStatement pst;
    Statement statement;
    ResultSet rs;
    Connection connection = null;
    String SQL;
    int currentRow = 0;

    static String cId;
    static String cPass;

    boolean openhome = true;
    
    String du;
    String dp;
    
    Preferences pref;

    public enum ROLE {

        admin,
        employee,
        intern;
    }

    public ROLE role = ROLE.employee;

    public Login() {
        initComponents();

        this.setLocationRelativeTo(null);
        
        
        myPreferences();

    }
    
    
    
    
    
    void myPreferences(){
        pref = Preferences.userRoot().node(this.getClass().getName());
        pref.put("username","admin");
        pref.put("password","admin");
        
        du = pref.get("username", "root");
        dp = pref.get("password", "root");
        
        try{
            pref.exportNode(new FileOutputStream("pref.xml"));
        }catch(Exception e){
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE,null,e);
        }
    }
    
    

    void setValues(String h, String u, String p, String d) {
        hostName = h;
        userName = u;
        password = p;
        database = d;
    }

    public void doConnect() {
        try {

            String host = "jdbc:mysql://" + hostName + "/" + database;
            String username = userName;
            String pass = password;

            connection = DriverManager.getConnection(host, username, pass);

        } catch (SQLException error) {
            System.out.println(error.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        loginBt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        loginPass = new javax.swing.JPasswordField();
        openServerSettings = new javax.swing.JCheckBox();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Impiger Internship ");
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 109, 181));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/impigerpic.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Raleway", 0, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Login ID");

        loginID.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        loginID.setToolTipText("Please enter your username");
        loginID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        loginID.setMargin(new java.awt.Insets(50, 50, 5, 5));
        loginID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Login Password");

        loginBt.setBackground(new java.awt.Color(0, 110, 181));
        loginBt.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        loginBt.setForeground(new java.awt.Color(255, 255, 255));
        loginBt.setText("Login");
        loginBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 109, 181));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        loginPass.setFont(new java.awt.Font("Raleway", 0, 48)); // NOI18N
        loginPass.setToolTipText("Please enter your password");
        loginPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginPass.setOpaque(false);
        loginPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginPassKeyPressed(evt);
            }
        });

        openServerSettings.setText("Open Server Settings");
        openServerSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openServerSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(loginPass, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addComponent(loginID))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel2))
                                .addContainerGap(12, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(openServerSettings)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(loginBt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(openServerSettings)
                .addGap(27, 27, 27)
                .addComponent(loginBt)
                .addGap(166, 166, 166))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtActionPerformed
        login();
    }//GEN-LAST:event_loginBtActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void loginPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginPassKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_loginPassKeyPressed

    private void openServerSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openServerSettingsActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_openServerSettingsActionPerformed

    private void loginIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginIDActionPerformed

    void openServerSettings() {
        setVisible(false);

        ServerSettings serverSettings = new ServerSettings();
        serverSettings.loginl = true;
        serverSettings.setVisible(true);
        serverSettings.setValues(hostName, userName, password, database);
    }

    Home.ROLE setHomeRoles() {
        if(role == ROLE.admin){
            
                return Home.ROLE.admin;
                
        }else if(role == ROLE.employee){
            
                return Home.ROLE.employee;
                
        }else if(role == ROLE.intern){
            
                return Home.ROLE.intern;
                
        }
        
        return Home.ROLE.employee;
    }

    void openHome() {

        if (openServerSettings.isSelected() && role == ROLE.admin) {
            openServerSettings();
        } else if (openServerSettings.isSelected() && role != ROLE.admin) {
            Home home = new Home();
            home.setValues(hostName, userName, password, database);
            home.role = setHomeRoles();
            home.roleSet();
            home.start();
            home.setVisible(true);
            JOptionPane.showMessageDialog(null, "Only admin can change server settings");
        }
        if (!openServerSettings.isSelected() && openhome) {
            setVisible(false);
            Home home = new Home();
            home.setValues(hostName, userName, password, database);
            home.role = setHomeRoles();
            home.roleSet();
            home.start();
            home.setVisible(true);
            JOptionPane.showMessageDialog(null, home.role);
        } else if (!openServerSettings.isSelected() && openhome) {
            setVisible(false);
            Home home = new Home();
            home.setValues(hostName, userName, password, database);
            home.role = setHomeRoles();
            home.roleSet();
            home.start();
            home.setVisible(true);
        }

    }

    void getCorrectID() {
        try {

            String query = "SELECT * FROM `users` WHERE `username`='" + lgID + "'";
            pst = connection.prepareStatement(query);
            rs = pst.executeQuery();

            if (rs.next()) {
                cId = rs.getString("username");
                cPass = rs.getString("password");

                String r = rs.getString("role");

                if (r.equals("admin")) {
                    role = ROLE.admin;
                } else if (r.equals("employee")) {
                    role = ROLE.employee;
                } else if (r.equals("intern")) {
                    role = ROLE.intern;
                }

            }

        } catch (Exception e) {
            cId = "admin";
            cPass = "password";
            role = ROLE.admin;
            openhome = false;
            openServerSettings.setSelected(true);
            JOptionPane.showMessageDialog(null, "Could not connect to the database! \n\n Please contact your Administrator", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    String lgID;
    String lgPass;

    void login() {
        doConnect();
        lgPass = loginPass.getText();
        lgID = loginID.getText();

        getCorrectID();

        if (lgID.equals(cId) && lgPass.equals(cPass)) {
            
            openHome();

        } else if (!lgID.equals(cId) || !lgPass.equals(cPass)) {
            loginPass.setText(null);
            JOptionPane.showMessageDialog(null, "Username or Password is wrong");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBt;
    private javax.swing.JTextField loginID;
    private javax.swing.JPasswordField loginPass;
    private javax.swing.JCheckBox openServerSettings;
    // End of variables declaration//GEN-END:variables
}
