/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopoly.bank;

import javax.swing.JOptionPane;

/**
 *
 * @author raj15
 */
public class Bank extends javax.swing.JFrame {

    /**
     * Creates new form Bank
     */
    public Bank() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transferfrom = new javax.swing.ButtonGroup();
        transferto = new javax.swing.ButtonGroup();
        paybankperson = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tax1raj = new javax.swing.JButton();
        salaryraj = new javax.swing.JButton();
        tax2raj = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        rajfunds = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tax1arpita = new javax.swing.JButton();
        salaryarpita = new javax.swing.JButton();
        tax2arpita = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        arpitafunds = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tax2prachi = new javax.swing.JButton();
        tax1prachi = new javax.swing.JButton();
        salaryprachi = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        prachifunds = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tax1preet = new javax.swing.JButton();
        tax2preet = new javax.swing.JButton();
        salarypreet = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        preetfunds = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        transfer = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        transferamount = new javax.swing.JTextArea();
        transferfromRaj = new javax.swing.JRadioButton();
        transferfromArpita = new javax.swing.JRadioButton();
        transferfromPrachi = new javax.swing.JRadioButton();
        transferfromPreet = new javax.swing.JRadioButton();
        transfertoRaj = new javax.swing.JRadioButton();
        transfertoPreet = new javax.swing.JRadioButton();
        transfertoPrachi = new javax.swing.JRadioButton();
        transfertoArpita = new javax.swing.JRadioButton();
        transferfrombank = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        statustext = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        paybankamount = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        arpitapaysbank = new javax.swing.JRadioButton();
        rajpaysbank = new javax.swing.JRadioButton();
        preetpaysbank = new javax.swing.JRadioButton();
        prachipaysbank = new javax.swing.JRadioButton();
        paybank = new javax.swing.JButton();
        start = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        restart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monopoly Bank");
        setBackground(new java.awt.Color(255, 9, 9));
        setForeground(new java.awt.Color(204, 204, 0));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("$ Bank $");

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jPanel2.setBackground(new java.awt.Color(228, 9, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Raj");

        tax1raj.setBackground(new java.awt.Color(153, 0, 0));
        tax1raj.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tax1raj.setForeground(new java.awt.Color(0, 51, 51));
        tax1raj.setText("$1000 Tax");
        tax1raj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tax1rajActionPerformed(evt);
            }
        });

        salaryraj.setBackground(new java.awt.Color(153, 0, 0));
        salaryraj.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        salaryraj.setForeground(new java.awt.Color(0, 51, 51));
        salaryraj.setText("Salary");
        salaryraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryrajActionPerformed(evt);
            }
        });

        tax2raj.setBackground(new java.awt.Color(153, 0, 0));
        tax2raj.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tax2raj.setForeground(new java.awt.Color(0, 51, 51));
        tax2raj.setText("$2000 Tax");
        tax2raj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tax2rajActionPerformed(evt);
            }
        });

        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        rajfunds.setEditable(false);
        rajfunds.setBackground(new java.awt.Color(255, 51, 51));
        rajfunds.setColumns(20);
        rajfunds.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        rajfunds.setForeground(new java.awt.Color(0, 51, 51));
        rajfunds.setRows(1);
        jScrollPane10.setViewportView(rajfunds);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Funds in bank account");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tax1raj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salaryraj))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(tax2raj)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(71, 71, 71))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tax1raj)
                    .addComponent(salaryraj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tax2raj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(120, 120, 120)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(153, 0, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Arpita");

        tax1arpita.setBackground(new java.awt.Color(153, 0, 204));
        tax1arpita.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tax1arpita.setText("$1000 Tax");
        tax1arpita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tax1arpitaActionPerformed(evt);
            }
        });

        salaryarpita.setBackground(new java.awt.Color(153, 0, 204));
        salaryarpita.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        salaryarpita.setText("Salary");
        salaryarpita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryarpitaActionPerformed(evt);
            }
        });

        tax2arpita.setBackground(new java.awt.Color(153, 0, 204));
        tax2arpita.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tax2arpita.setText("$2000 Tax");
        tax2arpita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tax2arpitaActionPerformed(evt);
            }
        });

        arpitafunds.setEditable(false);
        arpitafunds.setBackground(new java.awt.Color(204, 0, 204));
        arpitafunds.setColumns(20);
        arpitafunds.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        arpitafunds.setRows(1);
        jScrollPane9.setViewportView(arpitafunds);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Funds in bank account");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(tax1arpita)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salaryarpita))
                            .addComponent(jScrollPane9))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(141, 141, 141))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(32, 32, 32))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tax2arpita)
                .addGap(71, 71, 71))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tax1arpita)
                    .addComponent(salaryarpita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tax2arpita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(120, 120, 120)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Prachi");

        tax2prachi.setBackground(new java.awt.Color(240, 182, 73));
        tax2prachi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tax2prachi.setText("$2000 Tax");
        tax2prachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tax2prachiActionPerformed(evt);
            }
        });

        tax1prachi.setBackground(new java.awt.Color(240, 182, 73));
        tax1prachi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tax1prachi.setText("$1000 Tax");
        tax1prachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tax1prachiActionPerformed(evt);
            }
        });

        salaryprachi.setBackground(new java.awt.Color(240, 182, 73));
        salaryprachi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        salaryprachi.setText("Salary");
        salaryprachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryprachiActionPerformed(evt);
            }
        });

        prachifunds.setEditable(false);
        prachifunds.setBackground(new java.awt.Color(255, 255, 51));
        prachifunds.setColumns(20);
        prachifunds.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        prachifunds.setRows(1);
        prachifunds.setTabSize(4);
        jScrollPane8.setViewportView(prachifunds);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Funds in bank account");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(159, 159, 159))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tax1prachi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salaryprachi))
                    .addComponent(jScrollPane8))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(tax2prachi)
                        .addGap(17, 17, 17)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tax1prachi)
                    .addComponent(salaryprachi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tax2prachi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(120, 120, 120)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Preet");

        tax1preet.setBackground(new java.awt.Color(0, 51, 153));
        tax1preet.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tax1preet.setForeground(new java.awt.Color(255, 255, 255));
        tax1preet.setText("$1000 Tax");
        tax1preet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tax1preetActionPerformed(evt);
            }
        });

        tax2preet.setBackground(new java.awt.Color(0, 51, 153));
        tax2preet.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tax2preet.setForeground(new java.awt.Color(255, 255, 255));
        tax2preet.setText("$2000 Tax");
        tax2preet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tax2preetActionPerformed(evt);
            }
        });

        salarypreet.setBackground(new java.awt.Color(0, 51, 153));
        salarypreet.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        salarypreet.setForeground(new java.awt.Color(255, 255, 255));
        salarypreet.setText("Salary");
        salarypreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarypreetActionPerformed(evt);
            }
        });

        preetfunds.setEditable(false);
        preetfunds.setBackground(new java.awt.Color(0, 0, 255));
        preetfunds.setColumns(20);
        preetfunds.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        preetfunds.setForeground(new java.awt.Color(255, 255, 255));
        preetfunds.setRows(1);
        jScrollPane7.setViewportView(preetfunds);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Funds in bank account");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tax1preet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salarypreet))
                            .addComponent(jScrollPane7)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(tax2preet)
                        .addGap(27, 27, 27)))
                .addGap(84, 84, 84))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tax1preet)
                    .addComponent(salarypreet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tax2preet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(112, 112, 112)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(0, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("Transfer Funds");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("From");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("To");

        transfer.setBackground(new java.awt.Color(0, 204, 204));
        transfer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        transfer.setText("Transfer");
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Amount");

        transferamount.setBackground(new java.awt.Color(102, 255, 255));
        transferamount.setColumns(10);
        transferamount.setRows(1);
        jScrollPane5.setViewportView(transferamount);

        transferfrom.add(transferfromRaj);
        transferfromRaj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transferfromRaj.setText("Raj");
        transferfromRaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferfromRajActionPerformed(evt);
            }
        });

        transferfrom.add(transferfromArpita);
        transferfromArpita.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transferfromArpita.setText("Arpita");
        transferfromArpita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferfromArpitaActionPerformed(evt);
            }
        });

        transferfrom.add(transferfromPrachi);
        transferfromPrachi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transferfromPrachi.setText("Prachi");
        transferfromPrachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferfromPrachiActionPerformed(evt);
            }
        });

        transferfrom.add(transferfromPreet);
        transferfromPreet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transferfromPreet.setText("Preet");
        transferfromPreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferfromPreetActionPerformed(evt);
            }
        });

        transferto.add(transfertoRaj);
        transfertoRaj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transfertoRaj.setText("Raj");
        transfertoRaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfertoRajActionPerformed(evt);
            }
        });

        transferto.add(transfertoPreet);
        transfertoPreet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transfertoPreet.setText("Preet");
        transfertoPreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfertoPreetActionPerformed(evt);
            }
        });

        transferto.add(transfertoPrachi);
        transfertoPrachi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transfertoPrachi.setText("Prachi");
        transfertoPrachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfertoPrachiActionPerformed(evt);
            }
        });

        transferto.add(transfertoArpita);
        transfertoArpita.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transfertoArpita.setText("Arpita");
        transfertoArpita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfertoArpitaActionPerformed(evt);
            }
        });

        transferfrom.add(transferfrombank);
        transferfrombank.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transferfrombank.setText("Bank");
        transferfrombank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferfrombankActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(144, 144, 144)
                            .addComponent(transfer))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(transferfromPreet))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(transferfromArpita)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(transferfromRaj)
                                .addGap(206, 206, 206)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(transfertoArpita)
                                            .addComponent(transfertoRaj)
                                            .addComponent(transfertoPrachi)))
                                    .addComponent(transfertoPreet)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(71, 71, 71)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel6)))
                                .addGap(32, 32, 32)))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transferfrombank)
                            .addComponent(transferfromPrachi))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel16))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transferfromRaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transferfromPreet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transferfromPrachi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transferfromArpita))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(transfertoRaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transfertoPreet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transfertoPrachi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transfertoArpita)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(transfer))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transferfrombank)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        statustext.setEditable(false);
        statustext.setColumns(20);
        statustext.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        statustext.setRows(5);
        jScrollPane3.setViewportView(statustext);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel15.setText("Status");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel15)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(51, 204, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("Pay Bank");

        paybankamount.setBackground(new java.awt.Color(102, 204, 0));
        jScrollPane6.setViewportView(paybankamount);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Amount");

        paybankperson.add(arpitapaysbank);
        arpitapaysbank.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        arpitapaysbank.setText("Arpita");
        arpitapaysbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arpitapaysbankActionPerformed(evt);
            }
        });

        paybankperson.add(rajpaysbank);
        rajpaysbank.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rajpaysbank.setText("Raj");
        rajpaysbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rajpaysbankActionPerformed(evt);
            }
        });

        paybankperson.add(preetpaysbank);
        preetpaysbank.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        preetpaysbank.setText("Preet");
        preetpaysbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preetpaysbankActionPerformed(evt);
            }
        });

        paybankperson.add(prachipaysbank);
        prachipaysbank.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prachipaysbank.setText("Prachi");
        prachipaysbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prachipaysbankActionPerformed(evt);
            }
        });

        paybank.setBackground(new java.awt.Color(102, 204, 0));
        paybank.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        paybank.setText("Pay ");
        paybank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybankActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arpitapaysbank)
                            .addComponent(rajpaysbank)
                            .addComponent(prachipaysbank)))
                    .addComponent(preetpaysbank))
                .addGap(104, 104, 104)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(paybank))
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(40, 40, 40)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(rajpaysbank)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(preetpaysbank)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(prachipaysbank))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(32, 32, 32)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(arpitapaysbank))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(paybank)))
                        .addGap(40, 40, 40))))
        );

        start.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        quit.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        restart.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        restart.setText("Restart");
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(714, 714, 714)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(start)
                                        .addGap(199, 199, 199))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(quit)
                                        .addGap(205, 205, 205))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(restart)
                        .addGap(168, 168, 168))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(start)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(restart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quit)))
                        .addContainerGap(35, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salaryprachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryprachiActionPerformed
       String prachitaxfunds=prachifunds.getText();
       int tax=Integer.parseInt(prachitaxfunds)+2000;
       prachifunds.setText(Integer.toString(tax));
       statustext.setText(statustext.getText()+"\n - Prachi received $2000 Salary.");
    }//GEN-LAST:event_salaryprachiActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        statustext.setText(statustext.getText() +"\n********************************************************\n\t                   EXIT \n********************************************************");
        JOptionPane.showMessageDialog(null, "Exit");
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        paybankamount.setText(null);
        transferamount.setText(null);
        preetfunds.setText("10000");
        rajfunds.setText("10000");
        prachifunds.setText("10000");
        arpitafunds.setText("10000");
        statustext.setText("*********************************************************\n\t      The Game Has Started \n*********************************************************");
    }//GEN-LAST:event_startActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
        preetfunds.setText("10000");
        rajfunds.setText("10000");
        prachifunds.setText("10000");
        arpitafunds.setText("10000");
        statustext.setText("*********************************************************\n\t      The Game Has Restarted \n*********************************************************");
    }//GEN-LAST:event_restartActionPerformed

    private void tax1rajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tax1rajActionPerformed
        String rajtaxfunds=rajfunds.getText();
        int tax=Integer.parseInt(rajtaxfunds)-1000;
        rajfunds.setText(Integer.toString(tax));
        statustext.setText(statustext.getText()+"\n - Raj Payed $1000 Tax.");
    }//GEN-LAST:event_tax1rajActionPerformed

    private void tax1preetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tax1preetActionPerformed
        String preettaxfunds=preetfunds.getText();
        int tax=Integer.parseInt(preettaxfunds)-1000;
        preetfunds.setText(Integer.toString(tax));
        statustext.setText(statustext.getText()+"\n - Preet Payed $1000 Tax.");
    }//GEN-LAST:event_tax1preetActionPerformed

    private void tax1prachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tax1prachiActionPerformed
        String prachitaxfunds=prachifunds.getText();
        int tax=Integer.parseInt(prachitaxfunds)-1000;
        prachifunds.setText(Integer.toString(tax));
        statustext.setText(statustext.getText()+"\n - Prachi Payed $1000 Tax.");
    }//GEN-LAST:event_tax1prachiActionPerformed

    private void tax1arpitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tax1arpitaActionPerformed
        String arpitataxfunds=arpitafunds.getText();
        int tax=Integer.parseInt(arpitataxfunds)-1000;
        arpitafunds.setText(Integer.toString(tax));
        statustext.setText(statustext.getText()+"\n - Arpita Payed $1000 Tax.");
    }//GEN-LAST:event_tax1arpitaActionPerformed

    private void tax2rajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tax2rajActionPerformed
        String rajtaxfunds=rajfunds.getText();
        int tax=Integer.parseInt(rajtaxfunds)-2000;
        rajfunds.setText(Integer.toString(tax));
        statustext.setText(statustext.getText()+"\n - Raj Payed $2000 Tax.");
    }//GEN-LAST:event_tax2rajActionPerformed

    private void tax2preetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tax2preetActionPerformed
        String preettaxfunds=preetfunds.getText();
        int tax=Integer.parseInt(preettaxfunds)-2000;
        preetfunds.setText(Integer.toString(tax));
        statustext.setText(statustext.getText()+"\n - Preet Payed $2000 Tax.");
    }//GEN-LAST:event_tax2preetActionPerformed

    private void tax2prachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tax2prachiActionPerformed
       String prachitaxfunds=prachifunds.getText();
       int tax=Integer.parseInt(prachitaxfunds)-2000;
       prachifunds.setText(Integer.toString(tax));
       statustext.setText(statustext.getText()+"\n - Prachi Payed $2000 Tax.");
    }//GEN-LAST:event_tax2prachiActionPerformed

    private void tax2arpitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tax2arpitaActionPerformed
       String arpitataxfunds=arpitafunds.getText();
       int tax=Integer.parseInt(arpitataxfunds)-2000;
       arpitafunds.setText(Integer.toString(tax));
       statustext.setText(statustext.getText()+"\n - Arpita Payed $2000 Tax.");
    }//GEN-LAST:event_tax2arpitaActionPerformed

    private void salaryrajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryrajActionPerformed
       String rajtaxfunds=rajfunds.getText();
       int tax=Integer.parseInt(rajtaxfunds)+2000;
       rajfunds.setText(Integer.toString(tax));
       statustext.setText(statustext.getText()+"\n - Raj received $2000 Salary.");
    }//GEN-LAST:event_salaryrajActionPerformed

    private void salarypreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarypreetActionPerformed
        String preettaxfunds=preetfunds.getText();
       int tax=Integer.parseInt(preettaxfunds)+2000;
       preetfunds.setText(Integer.toString(tax));
       statustext.setText(statustext.getText()+"\n - Preet received $2000 Salary.");
    }//GEN-LAST:event_salarypreetActionPerformed

    private void salaryarpitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryarpitaActionPerformed
        String arpitataxfunds=arpitafunds.getText();
       int tax=Integer.parseInt(arpitataxfunds)+2000;
       arpitafunds.setText(Integer.toString(tax));
        statustext.setText(statustext.getText()+"\n - Arpita received $2000 Salary.");
    }//GEN-LAST:event_salaryarpitaActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
        
        String transferfundsamount=transferamount.getText();
        int fundsamount=Integer.parseInt(transferfundsamount);
        int x=fundsamount;
        statustext.setText(statustext.getText()+"\n - "+transferfrom.getSelection().getActionCommand()+" has sent $" +x +" to " +transferto.getSelection().getActionCommand());
        if ("Raj".equals(transferfrom.getSelection().getActionCommand())){
            int rajsent=Integer.parseInt(rajfunds.getText())-x;
            rajfunds.setText(Integer.toString(rajsent));
        }
        if ("Preet".equals(transferfrom.getSelection().getActionCommand())){
            int preetsent=Integer.parseInt(preetfunds.getText())-x;
            preetfunds.setText(Integer.toString(preetsent));
        }
        if ("Prachi".equals(transferfrom.getSelection().getActionCommand())){
            int prachisent=Integer.parseInt(prachifunds.getText())-x;
            prachifunds.setText(Integer.toString(prachisent));
        }
        if ("Arpita".equals(transferfrom.getSelection().getActionCommand())){
            int arpitasent=Integer.parseInt(arpitafunds.getText())-x;
            arpitafunds.setText(Integer.toString(arpitasent));
        }
//        ********************************************************************
        if ("Raj".equals(transferto.getSelection().getActionCommand())){
            int rajsent=Integer.parseInt(rajfunds.getText())+x;
            rajfunds.setText(Integer.toString(rajsent));
        }
        if ("Preet".equals(transferto.getSelection().getActionCommand())){
            int preetsent=Integer.parseInt(preetfunds.getText())+x;
            preetfunds.setText(Integer.toString(preetsent));
        }
        if ("Prachi".equals(transferto.getSelection().getActionCommand())){
            int prachisent=Integer.parseInt(prachifunds.getText())+x;
            prachifunds.setText(Integer.toString(prachisent));
        }
        if ("Arpita".equals(transferto.getSelection().getActionCommand())){
            int arpitasent=Integer.parseInt(arpitafunds.getText())+x;
            arpitafunds.setText(Integer.toString(arpitasent));
        }
        if ("Bank".equals(transferfrom.getSelection().getActionCommand())) {
        }
        transferamount.setText(null);
    }//GEN-LAST:event_transferActionPerformed

    private void transferfromRajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferfromRajActionPerformed
        transferfromRaj.setActionCommand("Raj");
    }//GEN-LAST:event_transferfromRajActionPerformed

    private void transfertoRajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfertoRajActionPerformed
        transfertoRaj.setActionCommand("Raj");
    }//GEN-LAST:event_transfertoRajActionPerformed

    private void transferfromPreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferfromPreetActionPerformed
        transferfromPreet.setActionCommand("Preet");
    }//GEN-LAST:event_transferfromPreetActionPerformed

    private void transferfromPrachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferfromPrachiActionPerformed
        transferfromPrachi.setActionCommand("Prachi");
    }//GEN-LAST:event_transferfromPrachiActionPerformed

    private void transferfromArpitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferfromArpitaActionPerformed
        transferfromArpita.setActionCommand("Arpita");
    }//GEN-LAST:event_transferfromArpitaActionPerformed

    private void transfertoPreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfertoPreetActionPerformed
        transfertoPreet.setActionCommand("Preet");
    }//GEN-LAST:event_transfertoPreetActionPerformed

    private void transfertoPrachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfertoPrachiActionPerformed
        transfertoPrachi.setActionCommand("Prachi");
    }//GEN-LAST:event_transfertoPrachiActionPerformed

    private void transfertoArpitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfertoArpitaActionPerformed
        transfertoArpita.setActionCommand("Arpita");
    }//GEN-LAST:event_transfertoArpitaActionPerformed

    private void paybankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybankActionPerformed
        
        String paybankfundsamount=paybankamount.getText();
        int fundsamount=Integer.parseInt(paybankfundsamount);
        int x=fundsamount;
        statustext.setText(statustext.getText()+"\n - "+paybankperson.getSelection().getActionCommand()+" has paid $" +x +" to the bank.");
        if ("Raj".equals(paybankperson.getSelection().getActionCommand())){
            int rajpaid=Integer.parseInt(rajfunds.getText())-x;
            rajfunds.setText(Integer.toString(rajpaid));
        }
        if ("Preet".equals(paybankperson.getSelection().getActionCommand())){
            int preetpaid=Integer.parseInt(preetfunds.getText())-x;
            preetfunds.setText(Integer.toString(preetpaid));
        }
        if ("Prachi".equals(paybankperson.getSelection().getActionCommand())){
            int prachipaid=Integer.parseInt(prachifunds.getText())-x;
            prachifunds.setText(Integer.toString(prachipaid));
        }
        if ("Arpita".equals(paybankperson.getSelection().getActionCommand())){
            int arpitapaid=Integer.parseInt(arpitafunds.getText())-x;
            arpitafunds.setText(Integer.toString(arpitapaid));
        }
        paybankamount.setText(null);
    }//GEN-LAST:event_paybankActionPerformed

    private void rajpaysbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rajpaysbankActionPerformed
        rajpaysbank.setActionCommand("Raj");
    }//GEN-LAST:event_rajpaysbankActionPerformed

    private void preetpaysbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preetpaysbankActionPerformed
        preetpaysbank.setActionCommand("Preet");
    }//GEN-LAST:event_preetpaysbankActionPerformed

    private void prachipaysbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prachipaysbankActionPerformed
        prachipaysbank.setActionCommand("Prachi");
    }//GEN-LAST:event_prachipaysbankActionPerformed

    private void arpitapaysbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arpitapaysbankActionPerformed
        arpitapaysbank.setActionCommand("Arpita");
    }//GEN-LAST:event_arpitapaysbankActionPerformed

    private void transferfrombankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferfrombankActionPerformed
        transferfrombank.setActionCommand("Bank");
    }//GEN-LAST:event_transferfrombankActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea arpitafunds;
    private javax.swing.JRadioButton arpitapaysbank;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton paybank;
    private javax.swing.JTextPane paybankamount;
    private javax.swing.ButtonGroup paybankperson;
    private javax.swing.JTextArea prachifunds;
    private javax.swing.JRadioButton prachipaysbank;
    private javax.swing.JTextArea preetfunds;
    private javax.swing.JRadioButton preetpaysbank;
    private javax.swing.JButton quit;
    private javax.swing.JTextArea rajfunds;
    private javax.swing.JRadioButton rajpaysbank;
    private javax.swing.JButton restart;
    private javax.swing.JButton salaryarpita;
    private javax.swing.JButton salaryprachi;
    private javax.swing.JButton salarypreet;
    private javax.swing.JButton salaryraj;
    private javax.swing.JButton start;
    private javax.swing.JTextArea statustext;
    private javax.swing.JButton tax1arpita;
    private javax.swing.JButton tax1prachi;
    private javax.swing.JButton tax1preet;
    private javax.swing.JButton tax1raj;
    private javax.swing.JButton tax2arpita;
    private javax.swing.JButton tax2prachi;
    private javax.swing.JButton tax2preet;
    private javax.swing.JButton tax2raj;
    private javax.swing.JButton transfer;
    private javax.swing.JTextArea transferamount;
    private javax.swing.ButtonGroup transferfrom;
    private javax.swing.JRadioButton transferfromArpita;
    private javax.swing.JRadioButton transferfromPrachi;
    private javax.swing.JRadioButton transferfromPreet;
    private javax.swing.JRadioButton transferfromRaj;
    private javax.swing.JRadioButton transferfrombank;
    private javax.swing.ButtonGroup transferto;
    private javax.swing.JRadioButton transfertoArpita;
    private javax.swing.JRadioButton transfertoPrachi;
    private javax.swing.JRadioButton transfertoPreet;
    private javax.swing.JRadioButton transfertoRaj;
    // End of variables declaration//GEN-END:variables
}
